name: Docker CI

env:
  TES3MP_VERSION: 0.8.1

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hotarublaze
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            TES3MP_VERSION=${{ env.TES3MP_VERSION }}
          tags: ghcr.io/hotarublaze/tes3mp-docker:${{env.TES3MP_VERSION}}